<?php
/**
 * @category   TechMitraa
 * @package    TechMitraa_StoreInfo
 * @author     bhavi.techmitraa@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace TechMitraa\StoreInfo\Setup;

use Magento\Framework\Setup\InstallSchemaInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\Framework\Setup\SchemaSetupInterface;
use Magento\Framework\DB\Ddl\Table;
/**
 * @codeCoverageIgnore
 */
class InstallSchema implements InstallSchemaInterface
{
    /**
     * {@inheritdoc}
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function install(SchemaSetupInterface $setup, ModuleContextInterface $context)
    {
		$installer = $setup;
		$installer->startSetup();

		/**
		 * Creating table techmitraa_storeinfo
		 */
		$table = $installer->getConnection()->newTable($installer->getTable('techmitraa_storeinfo'))
		->addColumn(
			'id',
			Table::TYPE_INTEGER,
			255,
			['identity' => true, 'unsigned' => true, 'nullable' => false, 'primary' => true],
			'ID'
		)->addColumn(
			'storename',
			Table::TYPE_TEXT,
			255,
			['nullable' => false,],
			'Store Name'
		)->addColumn(
			'store_address',
			Table::TYPE_TEXT,
			255,
			['nullable' => false],
			'Store Address'
		)->addColumn(
			'phone_number',
			Table::TYPE_INTEGER,
			10,
			['nullable' => true],
			'Phone Number'
		)->addColumn(
			'status',
			Table::TYPE_BOOLEAN,
			1,
			[ 'nullable' => false],
			'Status'
		)->addColumn(
			'hours_of_operation',
			Table::TYPE_TEXT,
			null,
			['nullable' => true],
			'Operation Hours'
		)->addColumn(
			'image',
			Table::TYPE_TEXT,
			null,
			['nullable' => true],
			'Store Image'
		)->addColumn(
			'created_at',
			Table::TYPE_TIMESTAMP,
			10,
			['nullable' => false],
			'Created At'
		)->addColumn(
			'updated_at',
			Table::TYPE_TIMESTAMP,
			10,
			['nullable' => false],
			'Updated At'
		);

		$installer->getConnection()->createTable($table);
		$installer->endSetup();
	}
}