<?php
/**
 * @category   TechMitraa
 * @package    TechMitraa_CustomSoreInfo
 * @author     bhavi.techmitraa@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace TechMitraa\StoreInfo\Model\Config\FrontendModel;
use Magento\Framework\Data\Form\Element\AbstractElement;

class OperationHours extends \Magento\Framework\Data\Form\Element\AbstractElement
{

    /**
     * Layout
     *
     * @var \Magento\Framework\View\LayoutInterface
     */
     protected $_layout;

    protected $element;

    /**
     *
     */
     public function __construct(
        \Magento\Framework\View\LayoutInterface $layout,
        \Magento\Framework\View\LayoutFactory $layoutFactory
     ) {
        $this->_layout = $layout;
        $this->layoutFactory = $layoutFactory;
     }




    public function render(\Magento\Framework\Data\Form\Element\AbstractElement $element)
    {

        $renderer = $this->layoutFactory->create()
            ->createBlock('TechMitraa\StoreInfo\Block\Adminhtml\TimeSlider');


        $renderer->setElement($this->element);

        return $renderer->toHtml();


        // here you can write your code.
        $customDiv = '<div style="width:600px;height:200px;margin:10px 0;border:2px solid #000" id="customdiv"><h1 style="margin-top: 12%;margin-left:40%;">Custom Div</h1></div>';
        return $customDiv;
    }

}
