<?php
/**
 * @category   TechMitraa
 * @package    TechMitraa_StoreInfo
 * @author     bhavi.techmitraa.@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace TechMitraa\StoreInfo\Block;

use Magento\Framework\View\Element\Template\Context;
use TechMitraa\StoreInfo\Model\StoreInfoFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * StoreInfo View block
 */
class StoreInfoView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var StoreInfo
     */
    protected $_storeinfo;
    public function __construct(
        Context $context,
        StoreInfoFactory $storeinfo,
        FilterProvider $filterProvider
    ) {
        $this->_storeinfo = $storeinfo;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('TechMitraa StoreInfo Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $storeinfo = $this->_storeinfo->create();
        $singleData = $storeinfo->load($id);
        if($singleData->getStoreInfoId() || $singleData['id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}