<?php
/**
 * @category   TechMitraa
 * @package    TechMitraa_StoreInfo
 * @author     bhavi.techmitraa.@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace TechMitraa\StoreInfo\Block;

use Magento\Framework\View\Element\Template\Context;
use TechMitraa\StoreInfo\Model\StoreInfoFactory;
/**
 * StoreInfo List block
 */
class StoreInfoListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var StoreInfo
     */
    protected $_storeinfo;
    public function __construct(
        Context $context,
        StoreInfoFactory $storeinfo
    ) {
        $this->_storeinfo = $storeinfo;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('TechMitraa StoreInfo Module List Page'));
        
        if ($this->getStoreInfoCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'techmitraa.storeinfo.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getStoreInfoCollection()
            );
            $this->setChild('pager', $pager);
            $this->getStoreInfoCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getStoreInfoCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $storeinfo = $this->_storeinfo->create();
        $collection = $storeinfo->getCollection();
        $collection->addFieldToFilter('status','1');
        //$storeinfo->setOrder('id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}